### PR TITLE
Retry failed requests and do not exit when a single artifact download…

### LINKED ISSUE #134: Retry failed requests and do not exit when a single artifact download failed
First of all, n3dr is AWESOME!

**What would you like to be added**:

- Retry failed requests
- Log a failed download and proceed to the next one.

**Why is this needed**:

On systems with a huge number of artifacts it takes a while to download everything and it's confusing when the whole process ended up because of a short network issue or in cases when artifact data is corrupted.

**Examples**:
```
# docker logs a5e206740344
time="2020-07-10T11:08:32Z" level=info msg="HomeDir: '/home/jenkins'"
time="2020-07-10T16:30:11Z" level=info msg="Assembling downloadURLs 'releases'"
 64656 / 74888 time="2020-07-10T21:06:13Z" level=fatal msg="Get \"https://nexus/service/rest/v1/assets?repository=releases&continuationToken=55258bea3c6fae8a1c9b8bc8d0c74cdc\": EOF"
 64735 / 74888   86.44% 43m17
```

That's sad when after 10 hours collecting URLs the process failed with EOF.

Or 
```
time="2020-07-12T08:46:39Z" level=fatal msg="URL: 'https://nexus/repository/releases/archetype-catalog.xml' does not seem to contain an artifactName"
```

This file could be uploaded by mistake, I don't remember, but that's not a reason to stop the backup process.

Or sometimes it happens: data file has been damaged on a filesystem or removed, so the backup process should not be interrupted, e.g.

```
 12 / 4442 [>------------------------------------------------------------------------------------------------------------------------------------------]   0.27% 01m01s
FATA[0279] ResponseCode: '500' and Message '500 javax.servlet.ServletException: org.sonatype.nexus.repository.storage.RetryDeniedException: Exceeded retry limit' for URL: https://nexus-dev/repository/thirdparty/com/oracle/oim/wlthint3client/10.3.6.0/wlthint3client-10.3.6.0.pom 
```

Thank you!

### PR DESCRIPTION
**Pull request by vsoloviov**
… failed

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

Not sure which kind should I choose, could you please advise and I'll update? Thank you.

**What this PR does / why we need it**:
- Retry failed requests
- Log a failed download and proceed to the next one.

**Which issue(s) this PR fixes**:

Fixes #134 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: cli/req.go [hunk 1]
```diff
@@ -40,7 +41,11 @@ func (n Nexus3) request(url string) ([]byte, string, error) {
 }
 
 func (n Nexus3) response(req *http.Request) ([]byte, string, error) {
-	resp, err := http.DefaultClient.Do(req)
+	retryClient := retryablehttp.NewClient()
+	retryClient.RetryMax = 5
+	retryClient.Logger = nil
```
Comment (vsoloviov) [inline cli/req.go:46]: I used https://github.com/hashicorp/go-retryablehttp here, it's nice, only one thing I want to highlight: by default it has debug logging. Even if I set Logger to logrus, it just wraps DEBUG messages inside logrus format and we still have a lot of noise. 

Disabling logger as I have disabled it looks fine, the only one thing - it's not reporting original error, only the last one which comes from `retryClient`.
E.g. original message: 
```
FATA[0279] ResponseCode: '500' and Message '500 javax.servlet.ServletException: org.sonatype.nexus.repository.storage.RetryDeniedException: Exceeded retry limit for URL: https://nexus-dev/repository/thirdparty/com/oracle/oim/wlthint3client/10.3.6.0/wlthint3client-10.3.6.0.pom 

```

How it looks after this change:

```
 12 / 4442 [>-------------------------------------------------------------------------------------------------------------------------------------------------]   0.27%
FATA[1160] Get https://nexus-dev/repository/thirdparty/com/oracle/oim/wlthint3client/10.3.6.0/wlthint3client-10.3.6.0.pom: GET https://nexus-dev.va/repository/thirdparty/com/oracle/oim/wlthint3client/10.3.6.0/wlthint3client-10.3.6.0.pom giving up after 6 attempts 
```

I tried to configure Logger to work with logrus, but no success here, I give up :)

**Comment by 030** [comment]
@vsoloviov Thank you for the PR!
